### ISSUE TITLE
UnboundLocalError: local variable 'genbank_file_to_analyse' referenced before assignment

### ISSUE THREAD

**Issue by sche2021** [afelten-Anses/NAuRA#3]
Hello,

I am giving the query sequences list (list.txt) where I specified the path of all queries fasta files and .gbk files (in the genome folder)

this is my command
**NAuRA -i genome -q list.txt -T 1 --withPhylo --keepBlastAln --nucl**

I have the following error:

**--> Select genbank not already analyzed
--> Check externals tools in PATH
/home/sche/naura/env/bin/blastn
/home/sche/naura/env/bin/blastp
/home/sche/naura/env/bin/pairdist.py
/home/sche/naura/env/bin/clustalo
/home/sche/naura/env/bin/sumtrees.py
Traceback (most recent call last):
  File "/home/sche/naura/env/bin/NAuRA", line 869, in <module>
    main()
  File "/home/sche/naura/env/bin/NAuRA", line 771, in main
    genbank_file_to_analyse = select_strain_to_analyse(Arguments.liste, genbank_files)
  File "/home/sche/naura/env/bin/NAuRA", line 192, in select_strain_to_analyse
    if len(genbank_file_to_analyse) == 0 :
UnboundLocalError: local variable 'genbank_file_to_analyse' referenced before assignment**

how to continue?

**Comment by NAM4T** [comment]
Having the same problem with thw test files. 
How do you solve it?
